import { Col, Row } from "antd";
import Head from "next/head";

import { fetchEntries } from "../helper/contentfull";

export default function Home({ items }) {
  console.log(items);
  return (
    <div>
      <Head>
        <title>کتاب فروشی |صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Row>
          {items.map((book) => (
            <Col span={6}>
              <img width="100%" src={book.fields.cover.fields.file.url} />
              <h1>{book.fields.title}</h1>
              <div>{book.fields.author}</div>
            </Col>
          ))}
        </Row>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const { items } = await fetchEntries("book");
  return {
    props: { items },
  };
}
